#!/bin/bash

cd -- "$(dirname "$0")"

set -m 

git pull 

npx netlify-cms-proxy-server &
echo $! > npx.pid

invoke livereload &
echo $! > invoke.pid

sleep 45

echo "------------------------------------------------------------"

echo "Go to http://localhost:8000/admin to edit blog"
echo "Go to http://localhost:8000 to view blog"

echo "Don't forget to run 'publish-blog' to publish the blog to yyhh.org"

echo "------------------------------------------------------------"

open "http://localhost:8000"
open "http://localhost:8000/admin"

fg
